version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - binance_networks

  crypto-trading:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trader
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./logs:/app/logs
      - ./config:/app/config
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    links:
      - redis
    networks:
      - binance_networks

networks:
  binance_networks:
    driver: bridge